### ISSUE TITLE
Please add secret generation from spec

### ISSUE THREAD

**Issue by wpoynter** [babylonhealth/shipcat#355]
Having just setup a lot of services for staging-us, the majority of the manual work remaining is generating the required secrets and putting them into Vault. A substantial chunk of the work was determining what is the correct spec for the secrets (i.e. how long should they be and what character sets should they use) and copying secrets from one service to another where they share them.

The new function could look a little like
```
secrets:
  - key: ENCRYPTION_KEY
     type: generate
     bits: 256
     chars: [0-9a-f]
  - key: ENCRYPTION_IV
     type: generate
     bits: 128
     chars: [0-9A-Za-z]
  - key: CORE_RUBY_SECRET_KEY_BASE
     type: copy
     service: core-ruby
     source: SECRET_KEY_BASE
```

We would leave the existing `env` section the same, referencing IN_VAULT for all of the above.
