### ISSUE TITLE
Allow shipcat and charts share deployment kind logic

### ISSUE THREAD

**Issue by clux** [babylonhealth/shipcat#382]
Currently magic properties either have certain assumptions (can't use kong with elb charts), and cause us to not have to do certain tests (no health check necessary on headless services), some cronjob only setups still require a deployment which causes a debian with `sleep: Inifinity` running using ~0 resources. Having the concepts of deployment vs. statefulset deploy makes this worse by having shipcat to know how to wait for upgrades / get logs / port-forward / shell into a pod.

These things can easily be fixed if we introduced the concept of **kinds** into shipcat. Here are some __preliminary__ suggested kinds:

### Deployment
Standard. Deployment only. Optional extra cronjobs, optional extra worker deployments.
Can't use volumeclaims. Must have a healthcheck.

### Stateful
Same as above, except all main properties are shunted to a stateful set. Required for persistent volume claims.

### Headless
Same as deployment, but can not have a healthcheck.

### Cron
No deployment at all. Just cronjobs. Can have volume claims.

**Comment by janslow** [comment]
A couple of ideas

# `mainWorkload` property
Introduce a `mainWorkload` key which contains all of the properties which only affect the deployment.

```yaml
# services/foo/manifest.yml
mainWorkload:
	# enabled: true # set to false for headless/cron types
	# kind: deployment # or use kind: stateless
	image: ...
	resources: ...
	env: ...
workers:
	foo-worker: ...
cronJobs:
	foo-hourly: ...
```

# `workloads` property
Rather than having multiple fields for all types of workloads, use a single object:

```yaml
# services/foo/manifest.yml
mainWorkload:
	# enabled: true # set to false for headless/cron types
	# kind: deployment # or use kind: stateless
	image: ...
	resources: ...
	env: ...
workers:
	foo-worker: ...
cronJobs:
	foo-hourly: ...
```

This allows any combination of workload to be used. E.g., a service could have two deployments (API + UI) or just CronJobs.

In addition, this'd make it easy to add other types of workloads (e.g., daemon set/Job).

**Comment by gleaver** [comment]
@janslow those two manifest snippets look identical - is that intended?

**Comment by clux** [comment]
I've updated @janslow 's comment with what he told me on slack.

**Comment by clux** [comment]
note that the `workloads` property is equivalent to this structure if we vectorised the various ones.

```yaml
name: foo
workloads:
  deployments:
   - name: foo-api
  workers:
  - name: foo-headless-worker
  cronjobs:
  - name: foo-hourly
```

this is going to be easier to pick up in the charts.
interestingly this is almost equivalent to the syntax we already have:

```yaml
workers:
- name: foo-headless-worker
cronjobs:
- name: foo-hourly
```

.. but with the main deployment properties on root.
