### ISSUE TITLE
rollout tracking broken for statefulset

### ISSUE THREAD

**Issue by clux** [babylonhealth/shipcat#447]
It currently just ensures there is `readyReplicas` equal to `mf.min_replicas()` which is usually true at the beginning of a rollout. We need to also wait for the new generation.

We could just wait until:

currentRevision == updateRevision
(from statefulset status - we can extend `StatefulSummary` in track.rs)

provided we track the updatedRevision just like we track the template hash in deployments.

**Comment by clux** [comment]
Though there is a better way of doing this. Find the `updateRevision` on the statefulset status after upgrade, then track number of ready pods with that controller-revision-hash set on the pods:

```
metadata:
  labels:
     controller-revision-hash: logstash-f6588b747
```

But the string hash comparison is good enough (even though it gives no progress bar).

**Comment by clux** [comment]
```yaml
collisionCount: 0
currentReplicas: 3
currentRevision: logstash-f6588b747
observedGeneration: 3
readyReplicas: 3
replicas: 3
updateRevision: logstash-f6588b747
updatedReplicas: 3
```

We can also kind of use `updatedReplicas` for the progress bar (but it is going to be marked as updated before it is ready).
